name: WakaTime status update 

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Runs at 12 am  '0 0 * * *'  UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update My Profile's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          # WakaTime API key stored in secrets, do not directly paste it here
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Automatic github token
          GH_TOKEN: ${{ github.token }}
          # Branch - newer GitHub repositories have "main" as default branch, change to main in that case, default is master
          BRANCH: "main"
          # Manual Commit messages - write your own messages here
          COMMIT_MSG: "Automated Coding Activity Update:alien:"
          SHOW_OS: "True"  
